exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [ commit ]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
#      - id: no-commit-to-branch
#        args: [ '--branch', 'master', '--branch', 'staging', '--branch', 'production' ]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [ '--line-length=120' ]
  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [ '--config=setup.cfg' ]
        additional_dependencies: [ flake8-isort ]
# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
