# Generated by Django 5.1.6 on 2025-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_alter_transition_from_state'),
        ('users', '0003_userinstancepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstancepermission',
            name='transactions',
            field=models.ManyToManyField(related_name='user_instance_permissions', to='states.transition'),
        ),
    ]
