# Generated by Django 5.1.6 on 2025-02-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinstancepermission_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInstancePermission',
        ),
    ]
