# Generated by Django 5.1.6 on 2025-02-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancepermission',
            name='is_transition_allowed',
        ),
    ]
